# -*- coding: utf-8 -*-
"""Tesseract.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q0pu3nQ1fCcbrjEBU1d5LzTxogcjPqCL
"""



"""### Install Tesseract and PyTesseract

First, we need to install Tesseract OCR engine (as a system dependency) and the `pytesseract` Python wrapper. We'll also install `Pillow` for image manipulation.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%shell
# apt update
# apt install -y tesseract-ocr
# pip install pytesseract Pillow

"""### Import Libraries and Download a Sample Image

Now, let's import the necessary libraries and download a sample image to perform text extraction on.
"""

import pytesseract
from PIL import Image
import requests
from io import BytesIO

# Using the local 'log.jpg' file for text extraction as requested.
# The image_url is no longer needed for local file loading.
img = Image.open('log.jpg')

print("Image 'log.jpg' loaded successfully from local filesystem.")
# Display the image (optional)
# display(img)

"""### Perform Text Extraction

Now, we'll use `pytesseract.image_to_string()` to extract text from the loaded image.
"""

extracted_text = pytesseract.image_to_string(img)

print("Extracted Text:")
print(extracted_text)